### PR TITLE
Add dockerRegistry and dockerCredential

### LINKED ISSUE #55: Jenkins: Allow docker based builds to use Docker login
Many times, our docker based builds fail to pull the images because of rate limiting. If we had the option in the build config to do a docker login first, we could avoid this issue. Possibly another param called `DOCKER_CREDS`?

```
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Docker Registry: Allows pulling Docker images
from a custom Docker repository. If used, must
use credential as well. Default will be DockerHub.

Docker Credential: Allows for Docker login when
pulling images. This is valuable for custom repositories
or to avoid rate limiting.

Fixes #55
Depends #104

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

I've tested with success on my end
1. Both blank
2. Creds set as string
3. Creds set as map of strings.

### CODE REVIEW

**Comment by M-Davies** [comment]
run tests

**Review by M-Davies — APPROVED** [review]
Looks good! Thanks for this :)

**Review by karianna — APPROVED** [review]
LGTM, refactoring to DRY can come later

**Comment by karianna** [comment]
@AdamBrousseau - will need a rebase

**Comment by AdamBrousseau** [comment]
@karianna  rebased

**Comment by karianna** [comment]
Doesn't seem to be caused by this PR but:

```
RepoHandlerTest > userDefaultsSetterAndGetterReturns() FAILED
    groovy.lang.MissingPropertyException: No such property: adoptJson for class: RepoHandlerTest
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
        at RepoHandlerTest.userDefaultsSetterAndGetterReturns(RepoHandlerTest.groovy:125)

RepoHandlerTest > adoptDefaultsGetterReturns() FAILED
    groovy.lang.MissingMethodException: No signature of method: static org.junit.jupiter.api.Assertions.assertEquals() is applicable for argument types: (Boolean) values: [true]
    Possible solutions: assertEquals(byte, byte), assertEquals(byte, java.lang.Byte), assertEquals(char, char), assertEquals(char, java.lang.Character), assertEquals(double, double), assertEquals(double, java.lang.Double)
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1568)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1554)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at RepoHandlerTest.adoptDefaultsGetterReturns(RepoHandlerTest.groovy:67)
```

**Comment by gdams** [comment]
run tests

**Review by gdams — APPROVED** [review]

**Pull request merged**
