### PR TITLE
update bisheng source repo to official OpenEuler mirror

### PR DESCRIPTION
**Pull request by feilongjiang**
Part of [update bisheng source repo and tag search rules #2523](https://github.com/AdoptOpenJDK/openjdk-build/pull/2523)

### CODE REVIEW

**Comment by M-Davies** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Putting in draft until 16 is released.

**Review by M-Davies — APPROVED** [review]

**Review by karianna — APPROVED** [review]
lgtm

**Pull request merged**
