### PR TITLE
Set User Defaults in RepoHandler

### PR DESCRIPTION
**Pull request by M-Davies**
* Follow up to #42
* Adds a new defaults.json param that pulls in and sets up the user defaults inside the RepoHandler class

### CODE REVIEW

**Comment by M-Davies** [comment]
Testing at https://ci.adoptopenjdk.net/job/build-scripts-testing/job/openjdk8-pipeline/122/console using my fork (generated with https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/testing/job/alpha-build-pipeline-generator/209/ and https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/testing/job/alpha_pipeline_jobs_generator/167/console)

**Comment by karianna** [comment]
Compilation failures.

**Comment by M-Davies** [comment]
> Compilation failures.

Unrealted (to be resolved by https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/56)

**Comment by karianna** [comment]
run tests

**Comment by karianna** [comment]
@M-Davies looks like genuine test failures this time.

**Comment by M-Davies** [comment]
> @M-Davies looks like genuine test failures this time.

They're expected to fail since the [test](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/src/test/groovy/RepoHandlerTest.groovy) is using the master branches config. I should probably add a note to the documentation explaining that actually...

**Comment by M-Davies** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
lgtm

**Pull request merged**
