### PR TITLE
Always Archive even if openjdk make fails so we archive failure logs

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Always archive artifacts so we capture make failure logs & dumps

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by karianna** [comment]
@gdams is it mans to be `run tests` or `run-tests`?

**Comment by andrew-m-leonard** [comment]
run-tests

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
