### PR TITLE
Remove groovy compilation

### PR DESCRIPTION
**Pull request by M-Davies**
* Renames docs and github check job to account for change

Fixes: #14 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Comment by karianna** [comment]
@M-Davies - I'm confused, won't this miss cases when we do change Groovy files and we don't compile to test them?

**Comment by M-Davies** [comment]
> @M-Davies - I'm confused, won't this miss cases when we do change Groovy files and we don't compile to test them?

We're already compiling and linting/checking groovy files after https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/37. I feel that the compile job is rather pointless now

**Comment by M-Davies** [comment]
Linting issue fixed by https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/42

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
PR tester failures unrelated (likely caused by https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/42 not being merged). The main thing is the removal of @Library hasn't affected how the pipelines run

**Review by karianna — APPROVED** [review]
It simplifies things, let's see if this works in practice.

**Comment by karianna** [comment]
@M-Davies - Not sure what to do about the pending/stuck tests here.  Do we need to land #42 first and come back to this?

**Comment by M-Davies** [comment]
> @M-Davies - Not sure what to do about the pending/stuck tests here. Do we need to land #42 first and come back to this?

That PR has landed. I'll rerun the tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by karianna** [comment]
run tests

**Comment by M-Davies** [comment]
> # 🟠 PR TESTER RESULT 🟠
> ❎ Some pipelines failed or the job was aborted! ❎
> _See the `pipeline-build-check` below for more information..._

Unrelated issues likely caused by https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/57#issuecomment-782045180 (will open an issue)

**Pull request merged**
