### PR TITLE
Running context class hudson.FilePath on node master

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
run tests

**Comment by karianna** [comment]
I don't think this PR is causing it, but the test failures are:

```
RepoHandlerTest > userDefaultsSetterAndGetterReturns() FAILED
    groovy.lang.MissingPropertyException: No such property: adoptJson for class: RepoHandlerTest
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
        at RepoHandlerTest.userDefaultsSetterAndGetterReturns(RepoHandlerTest.groovy:125)

RepoHandlerTest > adoptDefaultsGetterReturns() FAILED
    groovy.lang.MissingMethodException: No signature of method: static org.junit.jupiter.api.Assertions.assertEquals() is applicable for argument types: (Boolean) values: [true]
    Possible solutions: assertEquals(byte, byte), assertEquals(byte, java.lang.Byte), assertEquals(char, char), assertEquals(char, java.lang.Character), assertEquals(double, double), assertEquals(double, java.lang.Double)
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1568)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1554)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at RepoHandlerTest.adoptDefaultsGetterReturns(RepoHandlerTest.groovy:67)
```

**Comment by sophia-guo** [comment]
I think the failure is related with https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/src/test/groovy/RepoHandlerTest.groovy#L67 and
 https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/src/test/groovy/RepoHandlerTest.groovy#L68, which should use ` Assertions.assertTrue` instead of ` Assertions.assertEquals`.

I can update that if no others will do it.

**Comment by sophia-guo** [comment]
@karianna where can i find the output of those failures so I can make sure if there are other failures. I didn't find them at all checked jobs.

**Review by M-Davies — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @sophia-guo !

**Pull request merged**
