### PR TITLE
Rename jdk16 pipeline config to jdk16u

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Review by M-Davies — COMMENTED** [review]
@andrew-m-leonard Have you seen [this](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md#update-repository) section of RELEASING.md?

**Comment by andrew-m-leonard** [comment]
@M-Davies yes, it's what I am following, although some of the links are wrong

**Review by sxa — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Comment by M-Davies** [comment]
Twin PR https://github.com/AdoptOpenJDK/openjdk-build/pull/2533

**Review by M-Davies — CHANGES_REQUESTED** [review]
Could of docs references needing updating https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/search?q=jdk16

**Comment by andrew-m-leonard** [comment]
run tests

**Pull request merged**
