### PR TITLE
Add NODE_NAME to build description

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Add the name of the Node the build runs on
as a hyperlink in the Jenkins job description.
Append to the description if it is not null.

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
I find this very useful for debugging. It provides a quick glance to see what builds ran on what machines which can help identify problematic machines quickly.

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
Failing groovy test is due to https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/102

**Review by M-Davies — APPROVED** [review]
Looks really nice in the Jenkins view 👍

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
Thanks @AdamBrousseau - I've historically tended to just use a little shell script that parses the output but this makes a lot more sense :-)

**Pull request merged**
