### PR TITLE
Allow crossCompile config to specify variant

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Allow crossCompile job config to specify a Map for variants

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Review by M-Davies — CHANGES_REQUESTED** [review]
Can you also update our [new config documentation](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines#data-fields) to reflect this change?

**Review by M-Davies — APPROVED** [review]
LGTM

**Review by sxa — APPROVED** [review]
Sounds good - let's get this in and test through the pipelines. Although I'm not totally convinced https://github.com/AdoptOpenJDK/openjdk-build/pull/2520 is working yet for reasons I'm still trying to figure out

**Pull request merged**
