### PR TITLE
Pass in prBuilder to config_regeneration

### PR DESCRIPTION
**Pull request by M-Davies**
Adds in a new param for downstream generator that will denote if we are building inside the pr tester or not (also fixes some doc links that have been bugging me for a while)

Fixes: #64 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
run tests (likely requires approval)

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
Hmm now I'm hitting this error
```
12:04:03  Execution error: hudson.AbortException: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
[Pipeline] echo
12:04:03  hudson.AbortException: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
12:04:03  	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1157)
12:04:03  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1303)
12:04:03  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
12:04:03  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
12:04:03  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
12:04:03  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
12:04:03  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$541/000000000000000000.run(Unknown Source)
12:04:03  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12:04:03  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:04:03  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:04:03  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:04:03  	at java.lang.Thread.run(Thread.java:823)
```

**Comment by M-Davies** [comment]
It seems that the downstream jobs commit status messages are misleading too as they report the jobs as having passed when they actually haven't (FYI @gdams )

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM

**Review by gdams — APPROVED** [review]

**Pull request merged**
