### PR TITLE
Fix RepoHandlerTest

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
related with https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/108#issuecomment-805015922

**Comment by sophia-guo** [comment]
run tests

**Review by M-Davies — APPROVED** [review]
Thanks @sophia-guo ! I think I need to look into improving that test, it was very half thought when I first made it

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
run tests

**Pull request merged**
