### PR TITLE
Condense test details into one config file

### PR DESCRIPTION
**Pull request by M-Davies**
* Now easier for third parties to avoid release cycle test disabling and specify their own default test lists

Closes: #93 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
`Test / Groovy` is expected to fail (See prTester/ documentation for why)

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
Tester failures unrelated

**Review by karianna — APPROVED** [review]
LGTM

**Comment by M-Davies** [comment]
Running https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1443/console to test

**Pull request merged**
