### PR TITLE
Define available jenkins configuration parameters

### PR DESCRIPTION
**Pull request by M-Davies**
* Centralised location for groovy config param descriptions and usage
* Also deletes the FAQ.md of this repo as it's not being removed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2463

Part 1 of https://github.com/AdoptOpenJDK/openjdk-build/issues/2129
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
I'm not sure about a full removal of the FAQ.md. It is very difficult for people to get up to speed in stuff in our repositories and a basic document of "To do this, change this file" without all the background infromation is extremely valuable (I made a similar comment in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1974#pullrequestreview-598344190). If you really think we have no such content left then I mighe be ok with that, but it seems unlikely ...

**Comment by M-Davies** [comment]
@sxa The FAQ is still going to available in https://github.com/AdoptOpenJDK/openjdk-build, even after #2463. I'm just removing it from here so we don't have two duplicate FAQ's floating around

**Comment by sxa** [comment]
> available

There is stuff that would be specific to this repository - in fact a lot of the "end-user" stuff including running `make-adopt-build-farm.sh` vs `makejdk-any-platform.sh` could be in one here and expecting people to go to a repository about the pipelines for that and stuff like the "find your way around" chart and compiler prereqs seems a little odd so the information should perhaps be split between both repositories too.

**Comment by M-Davies** [comment]
> > available
> 
> There is stuff that would be specific to this repository - in fact a lot of the "end-user" stuff including running `make-adopt-build-farm.sh` vs `makejdk-any-platform.sh` could be in one here and expecting people to go to a repository about the pipelines for that and stuff like the "find your way around" chart and compiler prereqs seems a little odd so the information should perhaps be split between both repositories too.

In that case, would you prefer two FAQ's? One here and one in openjdk-build, each answering questions about their respective repositories?

**Comment by sxa** [comment]
> > > available
> > 
> > 
> > There is stuff that would be specific to this repository - in fact a lot of the "end-user" stuff including running `make-adopt-build-farm.sh` vs `makejdk-any-platform.sh` could be in one here and expecting people to go to a repository about the pipelines for that and stuff like the "find your way around" chart and compiler prereqs seems a little odd so the information should perhaps be split between both repositories too.
> 
> In that case, would you prefer two FAQ's? One here and one in openjdk-build, each answering questions about their respective repositories?

I think that's the only sensible choice unless the infromation specific to this repository is made available elsewhere in here.

**Review by karianna — APPROVED** [review]
LGTM

**Comment by M-Davies** [comment]
Twin PR for updating the FAQ of openjdk-build -> https://github.com/AdoptOpenJDK/openjdk-build/pull/2506

**Review by sxa — APPROVED** [review]
LGTM as far as I can tell - thanks :-)

**Pull request merged**
