### PR TITLE
Update auto test jobs generation

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix errors when generate test jobs.
 
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
run tests

**Comment by sophia-guo** [comment]
run tests

**Review by smlambert — APPROVED** [review]
thanks @sophia-guo for the revision, this is a tricky feature to test well (as we have to delete existing jobs to see it in action!)

**Review by M-Davies — APPROVED** [review]
Approve for merge post release

**Pull request merged**
