### PR TITLE
Inhibit nightly testing during JDK16 release cycle

### PR DESCRIPTION
**Pull request by sxa**
Title says it all - part of the standard release process.

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by sxa** [comment]
@tsc Approval to merge during the lockdown cycle please

**Review by M-Davies — APPROVED** [review]
LGTM for actually disabling the tests (the affected jobs might require a script approval but hopefully not 🤞)

**Comment by AdamBrousseau** [comment]
What's the best way for third parties to not pickup these types of temporary changes?
It looks like I could make copies and update my defaults.json. That runs the risk of my copies becoming stale.

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
👍 for disabling during release prep

**Comment by sxa** [comment]
> What's the best way for third parties to not pickup these types of temporary changes?

Suggest a separate issue covering that. I don't have an answer for it - it's been part of our release process for some time now (Although of others are using and shipping on the same cycles it may be worth considering doing the same).

**Pull request merged**
